# Pipeline configuration

# --- Input
inputdir: "data"
genome_extension: "{genome}.fna" 
dbdir: "databases" 
#metadata: "data/metadata.csv"

# --- Output directory
outdir: "results"
logdir: "results/logs"

# --- Evalues:
cog_evalue: "1e-5"
pfam_evalue: "1e-5"
merops_evalue: "1e-5"

# --- Pipelines to run
# Pfam: 
#    exec: True
# Cog: 
#    exec: True
# KEGG: 
#    exec: True
# CAZymes: 
#    exec: True
# Merops: 
#    exec: True