# Pipeline configuration

# --- Input
inputdir: "data"
genome_extension: "{genome}.fna" 
dbdir: "databases" 
metadata: "data/metadata.csv"

# --- Output directory
outdir: "results"
outdir_anno: "results/Annotation" 
logdir: "logs"

# --- Evalues:
cog_evalue: "1e-5"
pfam_evalue: "1e-5"

# --- Run Feature Selection (True or False)
FS: False

# Note: add metadata.csv to inputdir folder!