# Pipeline configuration

# --- Input
inputdir: "data"
genome_extension: "{genome}.fna" 
dbdir: "databases" 
metadata: "data/metadata.csv"

# --- Output directory
outdir: "results"
logdir: "results/logs"

# --- Evalues:
cog_evalue: "1e-5"
pfam_evalue: "1e-5"