# This file created by conda-build 3.10.9+36.gd10dbde.dirty
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/pygraphviz-feedstock/recipe, last modified Thu Jun 28 18:59:16 2018
# ------------------------------------------------

package:
    name: pygraphviz
    version: '1.3'
source:
    git_rev: pygraphviz-1.3
    git_url: https://github.com/pygraphviz/pygraphviz
    patches:
        - 0001-Fix-segmentation-faults-in-test_clear.py.patch
        - 0001-Merge-bytes-decoding-fix.patch
    sha256: ae621d143b7ad0a7d88d5766e8914ae06f960ee11e6daff26fe5836dfba40065
build:
    number: '1'
    script: python setup.py install --single-version-externally-managed --record=record.txt
        --include-path=$PREFIX/include --library-path=$PREFIX/lib
    string: py36h14c3975_1
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 had2808c_3
        - binutils_linux-64 7.2.0 had2808c_27
        - gcc_impl_linux-64 7.2.0 habb00fd_3
        - gcc_linux-64 7.2.0 h550dcbe_27
        - libstdcxx-ng 7.2.0 hdf63c60_3
    host:
        - ca-certificates 2018.03.07 0
        - cairo 1.14.12 h8948797_3
        - certifi 2018.4.16 py36_0
        - expat 2.2.5 he0dffb1_0
        - fontconfig 2.13.0 h9420a91_0
        - freetype 2.9.1 h8a8886c_0
        - fribidi 1.0.4 h14c3975_0
        - glib 2.56.1 h000015b_0
        - graphite2 1.3.11 h16798f4_2
        - graphviz 2.40.1 h21bd128_1
        - harfbuzz 1.7.6 hec2c2bc_3
        - icu 58.2 h9c2bf20_1
        - jpeg 9b h024ee3a_2
        - libedit 3.1.20170329 h6b74fdf_2
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 hdf63c60_3
        - libpng 1.6.34 hb9fc6fc_0
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - libtiff 4.0.9 he85c1e1_1
        - libuuid 1.0.3 h1bed415_2
        - libxcb 1.13 h1bed415_1
        - libxml2 2.9.8 h26e45fe_1
        - ncurses 6.1 hf484d3e_0
        - openssl 1.0.2o h20670df_0
        - pango 1.42.1 h8589676_0
        - pcre 8.42 h439df22_0
        - pixman 0.34.0 hceecf20_3
        - python 3.6.6 hc3d631a_0
        - readline 7.0 ha6073c6_4
        - setuptools 39.2.0 py36_0
        - sqlite 3.24.0 h84994c4_0
        - tk 8.6.7 hc745277_3
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 ha838bed_2
    run:
        - graphviz
        - libgcc-ng >=7.2.0
        - python >=3.6,<3.7.0a0
test:
    commands:
        - nosetests --verbosity=3 pygraphviz/tests
        - conda inspect linkages -p $PREFIX $PKG_NAME
    imports:
        - pygraphviz
        - pygraphviz.tests
    requires:
        - mock >=1.3
        - nose >=0.10.1
    source_files:
        - pygraphviz/tests
about:
    description: 'PyGraphviz is a Python interface to the Graphviz graph layout and

        visualization package. With PyGraphviz you can create, edit, read, write,

        and draw graphs using Python to access the Graphviz graph data structure

        and layout algorithms. PyGraphviz provides a similar programming

        interface to NetworkX (http://networkx.github.io).

        '
    dev_url: https://github.com/pygraphviz/pygraphviz
    doc_url: https://graphviz.readthedocs.io
    home: http://pygraphviz.github.io
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Python interface to Graphviz
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nehaljwani
